spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icalfilter
    username: postgresuser
    password: postgrespassword
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/icalfilter

#logging:
#  level:
#    root: debug