spring:
  application:
    name: icalfilter
  datasource:
    url: jdbc:postgresql://localhost:5432/icalfilter
    username: postgresuser
    password: postgrespassword
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migrations