spring:
  application:
    name: icalfilter
  datasource:
    url: ${POSTGRES_CONNECTION_STRING}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migrations
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.rumetshofer.dev/realms/icalfilter

server:
  error:
    whitelabel:
      enabled: false
  port: 8081